[package]
name = "pyo3-noir"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "pyo3_noir"
crate-type = ["cdylib"]

[dependencies]
noir = {git = "https://github.com/CanaliDavide/noir"}
pyo3 = "0.19.0"
